#!/usr/bin/env python3
"""
Debug why email is not sending
"""
import sys
sys.path.append('.')
from app.db.session import SessionLocal
from sqlalchemy import text

db = SessionLocal()

print("🔍 Checking what happened with case 183928001...")

# Check if follow-up was created
result = db.execute(text("""
    SELECT fa.attempt_id, fa.status, fa.response_status, fa.sent_at, fa.channel,
           fa.questions_count, fa.response_data
    FROM followup_attempts fa
    JOIN ae_cases c ON fa.case_id = c.case_id
    WHERE c.primaryid = 183928001
    ORDER BY fa.sent_at DESC
    LIMIT 5
"""))

attempts = result.fetchall()

if attempts:
    print(f"\n✅ Found {len(attempts)} follow-up attempts:")
    for att in attempts:
        print(f"\n  Attempt ID: {att[0]}")
        print(f"  Status: {att[1]}")
        print(f"  Response Status: {att[2]}")
        print(f"  Sent At: {att[3]}")
        print(f"  Channel: {att[4]}")
        print(f"  Questions: {att[5]}")
        if att[6] and 'questions' in att[6]:
            print(f"  Stored Questions: {len(att[6]['questions'])}")
else:
    print("\n❌ NO follow-up attempts found for case 183928001")
    print("   This means the trigger was SKIPPED or BLOCKED")
    print("\n   Possible reasons:")
    print("   1. ENABLE_EMAIL_FOLLOWUPS = False")
    print("   2. No questions generated by AI")
    print("   3. Duplicate check blocked it")
    print("   4. All questions already answered")

# Check for blocking attempts
result = db.execute(text("""
    SELECT COUNT(*) 
    FROM followup_attempts fa
    JOIN ae_cases c ON fa.case_id = c.case_id
    WHERE c.primaryid = 183928001
    AND fa.status IN ('PENDING', 'AWAITING_RESPONSE')
"""))
blocking = result.scalar()

if blocking > 0:
    print(f"\n⚠️ {blocking} PENDING/AWAITING_RESPONSE attempts BLOCKING new emails!")

db.close()
